#!/usr/bin/env python3

import argparse
import os
import shutil
import subprocess
import zipfile
from pathlib import Path


def javap_executable() -> str:
    java_home = os.environ.get("JAVA_HOME")
    if java_home:
        candidate = Path(java_home) / "bin" / "javap"
        if candidate.is_file():
            return str(candidate)
    executable = shutil.which("javap")
    if executable is None:
        raise RuntimeError("javap was not found; run with JDK 21")
    return executable


def public_surface(jar_path: Path) -> str:
    with zipfile.ZipFile(jar_path) as archive:
        classes = sorted(
            entry.filename[:-6].replace("/", ".")
            for entry in archive.infolist()
            if entry.filename.endswith(".class")
            and not entry.filename.startswith("META-INF/")
            and entry.filename != "module-info.class"
        )

    blocks = []
    javap = javap_executable()
    for class_name in classes:
        result = subprocess.run(
            [javap, "-classpath", str(jar_path), "-public", class_name],
            check=True,
            capture_output=True,
            text=True,
        )
        lines = [
            line.rstrip()
            for line in result.stdout.splitlines()
            if line and not line.startswith("Compiled from ")
        ]
        if not lines or "public " not in lines[0]:
            continue
        blocks.append("\n".join(lines))

    return (
        "# Generated by scripts/check_api_surface.py; update intentionally "
        "when the public SDK changes.\n\n"
        + "\n\n".join(blocks)
        + "\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("api_jar", type=Path)
    parser.add_argument("snapshot", type=Path)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()

    current = public_surface(args.api_jar)
    if args.write:
        args.snapshot.parent.mkdir(parents=True, exist_ok=True)
        args.snapshot.write_text(current)
        return 0

    if not args.snapshot.is_file():
        raise SystemExit(
            f"API surface snapshot is missing: {args.snapshot}; "
            "generate it intentionally with --write"
        )
    expected = args.snapshot.read_text()
    if current != expected:
        raise SystemExit(
            "Public API surface changed. Review compatibility and update "
            f"{args.snapshot} intentionally with --write."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
